#修改目标包名
package com.example.samples2

#修改app的名字
app_name 测试项目

#复制文件(如果对应的文件存在就覆盖掉)
copy_file app_icon.png src/main/res/drawable-hdpi/ic_launcher.png

#把src/main/java目录下所有文件中包含的字符串testString，替换为testString2
match_all src/main/ testString pretestStringsub

#把config.java的中的字符串github修改为aagithubbb
match_file src/main/java/com/example/samples/Config.java github aagithubbb
